In [6]:
library(dplyr)

In [7]:
nasa<-as_data_frame(nasa2)

In [8]:

nasa

      lat        long      month year cloudhigh cloudlow cloudmid ozone
1      36.200000 -113.8000 1     1995 26.0       7.5     34.5     304
2      33.704348 -113.8000 1     1995 20.0      11.5     32.5     304
3      31.208696 -113.8000 1     1995 16.0      16.5     26.0     298
4      28.713043 -113.8000 1     1995 13.0      20.5     14.5     276
5      26.217391 -113.8000 1     1995  7.5      26.0     10.5     274
6      23.721739 -113.8000 1     1995  8.0      30.0      9.5     264
7      21.226087 -113.8000 1     1995 14.5      29.5     11.0     258
8      18.730435 -113.8000 1     1995 19.5      26.5     17.5     252
9      16.234783 -113.8000 1     1995 22.5      27.5     18.5     250
10     13.739130 -113.8000 1     1995 21.0      26.0     16.5     250
11     11.243478 -113.8000 1     1995 19.0      28.5     12.5     248
12      8.747826 -113.8000 1     1995 16.5      28.0     13.5     248
13      6.252174 -113.8000 1     1995 17.5      33.0     18.5     250
14      3.756522 -113.8000 1     1995  5.5      44.5     13.0     248
15      1.260870 -113.8000 1     1995  0.5      43.5      4.0     248
16     -1.234783 -113.8000 1     1995  0.0      37.0      1.0     248
17     -3.730435 -113.8000 1     1995  0.5      29.0      1.5     248
18     -6.226087 -113.8000 1     1995  1.5      25.5      4.0     250
19     -8.721739 -113.8000 1     1995  1.5      27.0      4.5     252
20    -11.217391 -113.8000 1     1995  2.0      34.5      4.5     252
21    -13.713043 -113.8000 1     1995  4.0      34.5      3.5     254
22    -16.208696 -113.8000 1     1995  3.5      31.0      3.0     258
23    -18.704348 -113.8000 1     1995  2.5      34.0      4.0     258
24    -21.200000 -113.8000 1     1995  0.5      31.0      2.0     260
25     36.200000 -111.2957 1     1995 23.0       7.0     32.0     306
26     33.704348 -111.2957 1     1995 20.0      11.5     32.5     304
27     31.208696 -111.2957 1     1995 16.0      16.5     26.0     298
28     28.713043 -111.2957 1     1995 11.0      13.5     17.0     280
29     26.217391 -111.2957 1     1995  8.0      22.0     10.5     272
30     23.721739 -111.2957 1     1995 11.0      24.5     12.5     262
⋮     ⋮          ⋮         ⋮     ⋮    ⋮         ⋮        ⋮        ⋮
41443  -8.721739 -58.70435 12    2000 40.0       6.0     29.5     246
41444 -11.217391 -58.70435 12    2000 37.0       7.0     30.0     248
41445 -13.713043 -58.70435 12    2000 37.0       8.0     28.5     248
41446 -16.208696 -58.70435 12    2000 27.0      12.0     26.5     252
41447 -18.704348 -58.70435 12    2000 21.0      13.0     24.5     254
41448 -21.200000 -58.70435 12    2000 19.5      14.0     17.5     254
41449  36.200000 -56.20000 12    2000 16.5      38.5     30.0     280
41450  33.704348 -56.20000 12    2000 23.5      32.0     24.5     274
41451  31.208696 -56.20000 12    2000 22.0      27.0     23.5     268
41452  28.713043 -56.20000 12    2000 11.0      31.5     18.0     264
41453  26.217391 -56.20000 12    2000  4.5      30.5      8.0     262
41454  23.721739 -56.20000 12    2000  2.0      27.5      6.5     262
41455  21.226087 -56.20000 12    2000  0.5      31.0      3.5     262
41456  18.730435 -56.20000 12    2000  0.0      28.5      2.5     258
41457  16.234783 -56.20000 12    2000  0.5      28.5      4.0     258
41458  13.739130 -56.20000 12    2000  0.5      25.0      3.5     258
41459  11.243478 -56.20000 12    2000  1.0      24.5      4.5     254
41460   8.747826 -56.20000 12    2000  1.5      27.5      6.0     252
41461   6.252174 -56.20000 12    2000  4.0      21.5     18.0     246
41462   3.756522 -56.20000 12    2000  5.0      15.0     22.0     242
41463   1.260870 -56.20000 12    2000  4.0      15.5     15.0     242
41464  -1.234783 -56.20000 12    2000  7.5      15.5     17.5     242
41465  -3.730435 -56.20000 12    2000 17.0      12.5     26.0     242
41466  -6.226087 -56.20000 12    2000 34.5       7.5     32.0     246
41467  -8.721739 -56.20000 12    2000 40.5       7.5     32.0     248
41468 -11.217391 -56.20000 12    2000 40.0       6.5     30.5     252
41469 -13.713043 -56.20000 12    2000 40.5       6.5     28.5     250
41470 -16.208696 -56.20000 12    2000 31.0      11.5     28.5     250
41471 -18.704348 -56.20000 12    2000 26.0      14.5     23.0     252
41472 -21.200000 -56.20000 12    2000 23.5      14.5     21.0     254
      pressure surftemp temperature
1      835     272.7    272.1
2      940     279.5    282.2
3      960     284.7    285.2
4      990     289.3    290.7
5     1000     292.2    292.7
6     1000     294.1    293.6
7     1000     295.0    294.6
8     1000     298.3    296.9
9     1000     300.1    297.8
10    1000     300.1    298.7
11    1000     301.0    300.1
12    1000     301.0    300.1
13    1000     299.2    300.5
14    1000     298.7    299.6
15    1000     297.8    298.3
16    1000     298.3    297.8
17    1000     298.7    298.3
18    1000     299.2    298.3
19    1000     298.7    298.3
20    1000     298.3    298.3
21    1000     298.3    297.8
22    1000     297.8    296.9
23    1000     297.8    296.9
24    1000     297.4    296.9
25     810     270.9    270.3
26     940     279.5    282.2
27     960     284.7    285.2
28     950     286.8    286.8
29    1000     293.2    293.6
30    1000     295.0    295.0
⋮     ⋮        ⋮        ⋮
41443 1000     295.5    303.2
41444  985     294.6    302.8
41445  970     295.5    304.0
41446  985     298.3    304.0
41447  980     298.3    305.8
41448  980     300.1    303.6
41449 1000     291.2    290.2
41450 1000     293.6    291.7
41451 1000     294.1    294.1
41452 1000     295.5    295.5
41453 1000     297.4    296.5
41454 1000     297.8    296.9
41455 1000     297.8    297.4
41456 1000     298.3    297.8
41457 1000     298.3    297.8
41458 1000     298.3    298.3
41459 1000     298.7    299.2
41460 1000     298.7    299.6
41461 1000     296.0    300.1
41462  990     294.6    300.5
41463  985     295.5    302.3
41464 1000     297.4    303.6
41465 1000     297.8    303.6
41466  995     296.0    303.2
41467  990     294.6    301.9
41468  985     294.1    302.3
41469  960     295.0    303.6
41470  995     297.8    304.5
41471  995     299.6    304.9
41472  970     299.6    304.0

In [9]:
library(readr)
library(mechkar)
library(dplyr)
library(ggplot2)

In [22]:
train_test(data=nasa,train_name="train",test_name="test",prop=0.7,seed=5,tableone=TRUE)

Dataset partitioned into:

 + Train dataset: train

 + Test dataset: test

  |======================================================================| 100%

You got a perfectly balanced training and test datasets

   V1             V2           Pop
1  Individuals    n            41472
2  lat            Mean (SD)    7.5 (17.3)
3  lat            Median (IQR) 7.5 (-6.9-21.9)
4  long           Mean (SD)    -85.0 (17.3)
5  long           Median (IQR) -85.0 (-99.4--70.6)
6  month          Mean (SD)    6.5 (3.5)
7  month          Median (IQR) 6.5 (3.8-9.2)
8  year           Mean (SD)    1,997.5 (1.7)
9  year           Median (IQR) 1,997.5 (1,996.0-1,999.0)
10 cloudhigh      Mean (SD)    12.0 (12.4)
11 cloudhigh      Median (IQR) 8.5 (1.5-18.5)
12 cloudlow       Mean (SD)    26.2 (14.8)
13 cloudlow       Median (IQR) 23.5 (15.0-34.5)
14 cloudlow       Missing (%)  110 (0.3%)
15 cloudmid       Mean (SD)    15.3 (9.7)
16 cloudmid       Median (IQR) 14.0 (7.5-22.0)
17 ozone          Mean (SD)    267.2 (19.0)
18 ozone          Median (IQR) 264.0 (254.0-276.0)
19 pressure       Mean (SD)    985.4 (45.2)
20 pressure       Median (IQR) 1,000.0 (995.0-1,000.0)
21 surftemp       Mean (SD)    296.2 (4.7)
22 surftemp       Median (IQR) 296.9 (294.1-299.2)
23 temperature    Mean (SD)    297.9 (4.7)
24 temperature    Median (IQR) 299.2 (295.5-301.4)
25 traintest_ind_ Mean (SD)    1.3 (0.5)
26 traintest_ind_ Median (IQR) 1.0 (1.0-2.0)
   1                         2                         pval
1  29030                     12442                     NA
2  7.5 (17.3)                7.5 (17.2)                NA
3  7.5 (-6.2-23.7)           7.5 (-8.7-21.2)           0.92
4  -85.0 (17.3)              -85.0 (17.4)              NA
5  -83.7 (-98.8--71.2)       -86.3 (-101.3--68.7)      0.933
6  6.5 (3.5)                 6.5 (3.5)                 NA
7  6.0 (4.0-9.0)             7.0 (3.0-10.0)            0.756
8  1,997.5 (1.7)             1,997.5 (1.7)             NA
9  1,998.0 (1,996.0-1,999.0) 1,997.0 (1,996.0-1,999.0) 0.243
10 11.9 (12.3)               12.2 (12.5)               NA
11 8.0 (1.5-18.0)            8.5 (1.5-18.5)            0.02
12 26.3 (14.8)               26.2 (14.8)               NA
13 23.5 (15.0-34.5)          23.5 (15.0-34.5)          0.564
14 84 (0.3%)                 26 (0.2%)                 NA
15 15.3 (9.7)                15.3 (9.7)                NA
16 14.0 (7.5-22.0)           14.5 (7.5-22.0)           0.541
17 267.2 (19.0)              267.1 (18.9)              NA
18 264.0 (254.0-276.0)       264.0 (254.0-276.0)       0.638
19 985.5 (45.3)              985.4 (45.0)              NA
20 1,000.0 (995.0-1,000.0)   1,000.0 (995.0-1,000.0)   0.924
21 296.2 (4.7)               296.2 (4.7)               NA
22 296.9 (294.1-299.2)       296.9 (293.6-299.2)       0.973
23 297.9 (4.7)               297.9 (4.7)               NA
24 299.2 (295.5-301.4)       299.2 (295.5-301.4)       0.811
25 NA                        NA                        NA
26 NA                        NA                        0

In [23]:
rmse <- function(y,y_hat) {
    err <- sqrt(sum((y_hat-y)^2,na.rm=T)/length(y))
    return(err)
}

rmsle <- function(y,y_hat) {
    err <- sqrt(sum((log(y_hat+1)-log(y+1))^2,na.rm=T)/length(y))
    return(err)
}

In [24]:
err_res <- NULL

In [25]:
mod1 <- lm(temperature ~., data=train)
summary(mod1)

Call:
lm(formula = temperature ~ ., data = train)

Residuals:
     Min       1Q   Median       3Q      Max
-14.5414  -1.1222   0.0124   1.1644  16.2124

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept) -4.250e+02  1.322e+01 -32.149  < 2e-16 ***
lat         -3.642e-02  9.181e-04 -39.669  < 2e-16 ***
long         3.360e-03  7.010e-04   4.793 1.65e-06 ***
month        1.148e-01  3.253e-03  35.273  < 2e-16 ***
year         2.484e-01  6.629e-03  37.473  < 2e-16 ***
cloudhigh    2.858e-02  1.317e-03  21.704  < 2e-16 ***
cloudlow    -8.402e-02  1.077e-03 -78.026  < 2e-16 ***
cloudmid     6.319e-03  1.684e-03   3.753 0.000175 ***
ozone       -2.617e-02  8.087e-04 -32.354  < 2e-16 ***
pressure     3.378e-02  3.151e-04 107.206  < 2e-16 ***
surftemp     6.822e-01  3.006e-03 226.936  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.893 on 28935 degrees of freedom
  (84 observations deleted due to missingness)
Multiple R-squared:  0.8329,	Adjusted R-squared:  0.8329
F-statistic: 1.443e+04 on 10 and 28935 DF,  p-value: < 2.2e-16

In [26]:
pred1 <- predict(mod1,newdata=test)
pred2 <- predict(mod1,newdata=train)
rmse(test$temperature,pred1)
rmsle(test$temperature,pred1)
rmse(train$temperature,pred2)
rmsle(train$temperature,pred2)
err_res <- rbind(err_res, data.frame(Name="Base Linear regression", Model="mod1", 
                                     test_RMSE=rmse(test$temperature,pred1), 
                                     test_RMSLE=rmsle(test$temperature,pred1),
                                   train_RMSE=rmse(train$temperature,pred2), 
                                     train_RMSLE=rmsle(train$temperature,pred2)))
err_res

[1] 1.887186

[1] 0.006367224

[1] 1.88956

[1] 0.006373043

  Name                   Model test_RMSE test_RMSLE  train_RMSE train_RMSLE
1 Base Linear regression mod1  1.887186  0.006367224 1.88956    0.006373043

In [ ]:
#we can see that the model gave me Adjusted R-squared:  0.8329 but when we compare the train and the test errors it seems that they are similar

In [16]:
library(tree)
library(rpart)

In [27]:
mod3 <- tree(temperature ~., data=train)
mod3

node), split, n, deviance, yval
      * denotes terminal node

 1) root 28946 620500 298.0
   2) surftemp < 293.4 6247 160600 292.3
     4) surftemp < 286.55 969  19500 284.5 *
     5) surftemp > 286.55 5278  71540 293.7
      10) lat < 27.4652 4018  45850 294.6
        20) pressure < 817.5 201   3221 286.8 *
        21) pressure > 817.5 3817  29710 295.0
          42) cloudhigh < 31.75 3304  19480 294.5 *
          43) cloudhigh > 31.75 513   3535 298.4 *
      11) lat > 27.4652 1260  12500 290.9 *
   3) surftemp > 293.4 22699 201100 299.5
     6) surftemp < 297.6 10470  93940 298.0
      12) cloudlow < 18.75 3978  31390 300.1
        24) pressure < 947.5 315   5619 294.5 *
        25) pressure > 947.5 3663  15170 300.6 *
      13) cloudlow > 18.75 6492  34370 296.7
        26) lat < 24.9696 5196  19240 297.2 *
        27) lat > 24.9696 1296   8526 294.7 *
     7) surftemp > 297.6 12229  59790 300.9
      14) surftemp < 300.3 7235  32530 300.2 *
      15) surftemp > 300.3 4994  18490 301.9 *

In [37]:
pred3 <- predict(mod3,newdata=test)
pred4 <- predict(mod3,newdata=train)
rmse(test$temperature,pred3)
rmsle(test$temperature,pred3)
rmse(train$temperature,pred4)
rmsle(train$temperature,pred4)
err_res <- rbind(err_res, data.frame(Name="Decision Trees-tree", Model="mod3", 
                                     test_RMSE=rmse(test$temperature,pred3), 
                                     test_RMSLE=rmsle(test$temperature,pred3),
                                   train_RMSE=rmse(train$temperature,pred4), 
                                     train_RMSLE=rmsle(train$temperature,pred4)))
err_res

[1] 2.360892

[1] 0.007986039

[1] 2.366747

[1] 0.00800634

  Name                   Model test_RMSE test_RMSLE  train_RMSE train_RMSLE
1 Base Linear regression mod1  1.887186  0.006367224 1.889560   0.006373043
2 Base Linear regression mod1  2.360892  0.007986039 2.366747   0.008006340
3 Decision Trees-tree    mod3  2.360892  0.007986039 2.366747   0.008006340

In [30]:
library(randomForest)
library(ranger)

randomForest 4.6-14

Type rfNews() to see new features/changes/bug fixes.


Attaching package: ‘randomForest’


The following object is masked from ‘package:ggplot2’:

    margin


The following object is masked from ‘package:dplyr’:

    combine



Attaching package: ‘ranger’


The following object is masked from ‘package:randomForest’:

    importance

In [31]:
mod6 <- ranger(temperature ~., data=train)
mod6

ERROR: Error: Missing data in columns: cloudlow.

In [32]:
getMissingness(nasa)

[[1]]
       var na_count rate
1 cloudlow      110  0.3

[[2]]
[1] "This dataset has 41362 (99.7%) complete rows. Original data has 41472 rows."

$missingness
       var na_count rate
1 cloudlow      110  0.3

$message
[1] "This dataset has 41362 (99.7%) complete rows. Original data has 41472 rows."

$rows
NULL

In [63]:
mm <- getMissingness(train,getRows = T)

[[1]]
       var na_count rate
1 cloudlow       84  0.3

[[2]]
[1] "This dataset has 28946 (99.7%) complete rows. Original data has 29030 rows."

In [66]:
mm1 <- getMissingness(test,getRows = T)

[[1]]
       var na_count rate
1 cloudlow       26  0.2

[[2]]
[1] "This dataset has 12416 (99.8%) complete rows. Original data has 12442 rows."

In [77]:
train1 <- train[mm$rows,]
test1 <- test[mm$rows,]

In [78]:
train1 <- train1[,setdiff(names(train1),"cloudlow")] # in order to deleat the column with the NULL from the train and test
test1 <- test1[,setdiff(names(test1),"cloudlow")]

In [79]:
mod6 <- ranger(temperature ~., data=train1)
mod6

Ranger result

Call:
 ranger(temperature ~ ., data = train1)

Type:                             Regression
Number of trees:                  500
Sample size:                      28946
Number of independent variables:  9
Mtry:                             3
Target node size:                 5
Variable importance mode:         none
Splitrule:                        variance
OOB prediction error (MSE):       0.9987811
R squared (OOB):                  0.9534063

In [81]:
pred5 <- predict(mod6,test1)
pred6 <- predict(mod6,train1)
rmse(test1$temperature,pred5)
rmsle(test1$temperature,pred5)
rmse(train1$temperature,pred6)
rmsle(train1$temperature,pred6)
err_res <- rbind(err_res, data.frame(Name="Random_Forest", Model="mod6", 
                                     test_RMSE=rmse(test1$temperature,pred5), 
                                     test_RMSLE=rmsle(test1$temperature,pred5),
                                   train_RMSE=rmse(train1$temperature,pred6), 
                                     train_RMSLE=rmsle(train1$temperature,pred6)))
err_res

ERROR: Error: Missing data in columns: lat, long, month, year, cloudhigh, cloudmid, ozone, pressure, surftemp.

In [74]:
pred5

ERROR: Error in eval(expr, envir, enclos): object 'pred5' not found